### ISSUE TITLE
[Bug report] macOS 11.3: title bar buttons (close, minimize, maximize) do not work

### ISSUE THREAD

**Issue by ghost** [oleg68/GrandOrgue#19] opened 2021-04-27 11:02 UTC
I observed a problem under macOS 11.3. The three colored dots on the title bar do not work for custom windows. They work for the main window (what I mean with the main window can be seen on the attached screenshot), but not for the windows of the sample set.

![Screenshot](https://user-images.githubusercontent.com/82236523/116231049-add04400-a758-11eb-924a-9d0ea2af6281.jpg)

**Comment by oleg68** [comment] 2021-04-27 20:10
Could yyou try the release: https://github.com/oleg68/GrandOrgue/releases/download/0.3.1.2338-3.os/grandorgue-0.3.1.2338-3.os.osx.x86_64.dmg

It works fine with bar buttons in my 11.2. Look at the video: https://drive.google.com/file/d/1HGE12RPOnGzXlS9FIcAzWeTcTO4bhVHL/view?usp=sharing

**Comment by uctcs** [comment] 2021-04-27 22:28
It seems to be an issue with my installation. I created a new user. With the new instance, it works as expected. I checked my launch agents and launch daemons, but I can't find the culprit. GrandOrgue is the only misbehaving program I found so far.

**Comment by oleg68** [comment] 2021-04-28 19:21
Could you try to rename GrandOrgueConfig file and GrandOrgue directories in your home directory just for testing?

**Comment by uctcs** [comment] 2021-04-29 05:24
I tried the following things:

- I renamed (removed) the GrandOrgueConfig file.
- I reinstalled macOS from the recovery console.
- I temporarily disabled all LaunchAgents and LaunchDaemons (in /Library and in ~/Library)

No success. As GO works perfectly in another instance I probably have to make a fresh OS installation.

**Comment by uctcs** [comment] 2021-04-29 08:42
The second problem is probably associated with the button issue. GrandOrgue does not open additional windows.

https://user-images.githubusercontent.com/82236523/116524252-750aa900-a8d7-11eb-827b-895a717d040c.mov

**Comment by oleg68** [comment] 2021-04-29 12:25
I can neigher view nor download this video. Can you upload it to some file sharing host?

**Comment by oleg68** [comment] 2021-04-29 12:33
> t seems to be an issue with my installation. I created a new user. With the new instance, it works as expected. 
> I reinstalled macOS from the recovery console. No success.

Seems some user-wide UI settings prevent this from working. A new user has settings created from scratch, but reinstalling macos keeps the old user settings.

Did you try tha same GO build for the new user? Have you tried install the release version from GitHub?

**Comment by uctcs** [comment] 2021-04-29 14:39
Yes, I installed the latest version of GO.

Here you can download the video: https://www.dropbox.com/t/iLuB4Ws3vv1EsrdF.

**Comment by oleg68** [comment] 2021-04-29 20:10
I managed to reproduce the issue with additional pannels in GrandOrgue 0.3.1.3238-3.os on both osx 10.15 and 11.2. But the buttons work. So please create a separate issue for opening pannels.

**Comment by uctcs** [comment] 2021-04-30 01:47
Done. The buttons work now, but the maximize button opens a black fullscreen windw (as shown in the video).

**Comment by oleg68** [comment] 2021-05-03 17:45
The black fullscreen issue should be fixed with the same changes as #22 Try the build

**Comment by uctcs** [comment] 2021-05-03 17:55
Unfortunately, nothing has changed. I attach 2 crash reports and one error message.

[Archiv.zip](https://github.com/oleg68/GrandOrgue/files/6416711/Archiv.zip)

**Comment by oleg68** [comment] 2021-05-03 19:30
Has the maximize been fixed with grandorgue-0.3.1.2338-3.os.12.osx.x86_64.dmg?

**Comment by oleg68** [comment] 2021-05-05 19:34
Does maximise work just after deleting the saved state directory?

**Comment by uctcs** [comment] 2021-05-05 21:08
Yes, and also the panels open. These two issues seem to be linked.

**Comment by uctcs** [comment] 2021-05-23 00:05
Any chance to get the `com.our-organ.GrandOrgue.savedState`issue solved? As soon as this file appears the reported problem returns.

The state of GO does not seem to be saved in this file. For example, if I select a stop and then call GrandOrgue > File > Save the stop is still selected next time I start GO, even if I delete the above-mentioned file.

I tried to delete the files within this folder and locked the folder. This seems to work. I do not get any error message from GO trying to write the files. But from time to time GO crashes when quitting. I assume this happens when GO tries to write into the locked folder.

**Comment by oleg68** [comment] 2021-05-23 05:55
>  But from time to time GO crashes when quitting. 

Could you attach the crash report?

>  I assume this happens when GO tries to write into the locked folder.

If so, then there is a high chance that the issue can be fixed using the crash report. 

Otherwise I don't have any ideas how to fix it, because GO doesn't use saved states at all, and it is too difficult to discover why someone (maybe MacOS itself) tries to write the saved state.

**Comment by uctcs** [comment] 2021-05-23 07:05
[GrandOrgue_2021-05-23-014335_MacBook-Pro.crash.zip](https://github.com/oleg68/GrandOrgue/files/6527664/GrandOrgue_2021-05-23-014335_MacBook-Pro.crash.zip)

Hope this helps.

**Comment by oleg68** [comment] 2021-05-23 10:43
> Hope this helps.

I can eliminate this crash, but, unfortunally, it willn't help with this issue. This crash was not related with attempt to write savedState.

**Comment by oleg68** [comment] 2021-09-11 13:30
Since GrandOrgue started to build with wxWidgets 3.1, the issue is no more reproducible.

Seems it was a wxWidgets 3.0 bug.

Please reopen the issue if the problem appears again with the recent release of GrandOrgue.

**Closed by oleg68** 2021-09-11 13:30 UTC
